version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports: ["3000:3000"]
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REPOS_PATH: /var/repos
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASS: ${BASIC_AUTH_PASS}
    volumes:
      - ${REPOS_PATH}:/var/repos:ro

  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    profiles: ["build"]
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REPOS_PATH: /var/repos
      TRIGGER_TYPE: manual
    volumes:
      - ${REPOS_PATH}:/var/repos:ro
